services:
  nginx:
    image: braisenly/nginx-h3:stable
    container_name: nginx
    build:
      context: .
    env_file: .env
    environment:
      - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_STAGING=${CERTBOT_STAGING}
      - TZ=${TZ}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./tests:/static:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./html/maintenance.html:/var/www/html/maintenance.html
      - ./local/localhost.crt:/etc/nginx/local/localhost.crt:ro
      - ./local/localhost.key:/etc/nginx/local/localhost.key:ro
      - ./tests/njs:/opt/njs:rw
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
      - letsencrypt_logs:/var/log/letsencrypt:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bkend_lab
      - homepage_network
      - web_network
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    user: root
    #command: ["nginx", "-g", "daemon-off"]

volumes:
  certbot: 
  letsencrypt_logs:
    name: letsencrypt_logs

networks:
  bkend_lab:
    name: bkend_lab
    external: true
  homepage_network:
    name: homepage_network
  web_network:
    name: web_network
