version: '3.8'

services:
  nginx:
    image: braisenly/nginx-h3:test
    container_name: nginx
    env_file: .env
    environment:
      - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_STAGING=${CERTBOT_STAGING}
      - TZ=${TZ}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./ssl_common.conf:/etc/nginx/conf.d/ssl_common.conf
      - ./start.sh:/usr/local/bin/start.sh
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/html
      - letsencrypt_logs:/var/log/letsencrypt
      - letsencrypt_lib:/var/lib/letsencrypt
    networks:
      - web_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    user: root
    command: ["/bin/bash", "/usr/local/bin/start.sh"]

volumes:
  letsencrypt_certs:
    name: letsencrypt_certs
  letsencrypt_www:
    name: letsencrypt_www
  letsencrypt_logs:
    name: letsencrypt_logs
  letsencrypt_lib:
    name: letsencrypt_lib

networks:
  web_network:
    name: web_network
